<?php
/**
 * One-off / re-runnable importer: turns a JSON course list (see
 * docs/content/source/courses_parsed.json for the shape) into a SQL file
 * that can be reviewed, then imported alongside database/seed.sql.
 *
 * Usage:
 *   php database/tools/import_courses.php <input.json> <output.sql>
 *
 * Why this exists: CPI's course catalogue is real client content that
 * changes over time (new courses, updated pricing). Rather than hand-
 * writing INSERT statements whenever the client sends an updated list,
 * re-run this against a freshly exported JSON (same shape) to regenerate
 * database/seed_courses.sql.
 */

if ($argc < 3) {
    fwrite(STDERR, "Usage: php import_courses.php <input.json> <output.sql>\n");
    exit(1);
}

require __DIR__ . '/../../app/Support/Str.php';

use App\Support\Str;

$input = $argv[1];
$output = $argv[2];

$courses = json_decode(file_get_contents($input), true);
if (!is_array($courses)) {
    fwrite(STDERR, "Could not parse $input as a JSON array.\n");
    exit(1);
}

/** Canonical category taxonomy — slug => display name. */
$categories = [
    'accounting-audit-taxation' => 'Accounting, Audit & Taxation',
    'agriculture-environmental-management' => 'Agriculture & Environmental Management',
    'business-management' => 'Business Management',
    'communication-soft-skills' => 'Communication & Soft Skills',
    'education-training' => 'Education & Training',
    'governance-risk-compliance' => 'Governance, Risk & Compliance',
    'human-resource-management' => 'Human Resource Management',
    'information-technology-ai' => 'Information Technology & Artificial Intelligence',
    'leadership-executive-development' => 'Leadership & Executive Development',
    'legal-public-policy' => 'Legal & Public Policy',
    'meal' => 'Monitoring, Evaluation, Accountability & Learning (MEAL)',
    'procurement-logistics-supply-chain' => 'Procurement, Logistics & Supply Chain',
    'project-management' => 'Project Management',
    'public-health-healthcare-management' => 'Public Health & Healthcare Management',
    'languages' => 'Languages',
    'specialized-programmes' => 'Specialized Programmes',
];

/** Raw category label (as it appears in either source file) => canonical slug. */
$categoryMap = [
    // Short_Professional_Courses.xlsx labels
    'ICT & AI' => 'information-technology-ai',
    'ICT' => 'information-technology-ai',
    'Business' => 'business-management',
    'Environment' => 'agriculture-environmental-management',
    'Finance' => 'accounting-audit-taxation',
    'Governance' => 'governance-risk-compliance',
    'Human Resource' => 'human-resource-management',
    'Language' => 'languages',
    'Leadership' => 'leadership-executive-development',
    'MEAL' => 'meal',
    'Procurement' => 'procurement-logistics-supply-chain',
    'Project Management' => 'project-management',
    'Public Health' => 'public-health-healthcare-management',
    'Specialized' => 'specialized-programmes',
    // More__Professional_Training_Courses.xlsx labels (already close to canonical)
    'Accounting, Audit & Taxation' => 'accounting-audit-taxation',
    'Agriculture & Environmental Management' => 'agriculture-environmental-management',
    'Business Management' => 'business-management',
    'Communication & Soft Skills' => 'communication-soft-skills',
    'Education & Training' => 'education-training',
    'Governance, Risk & Compliance' => 'governance-risk-compliance',
    'Human Resource Management' => 'human-resource-management',
    'Information Technology & Artificial Intelligence' => 'information-technology-ai',
    'Leadership & Executive Development' => 'leadership-executive-development',
    'Legal & Public Policy' => 'legal-public-policy',
    'Procurement, Logistics & Supply Chain' => 'procurement-logistics-supply-chain',
    'Public Health & Healthcare Management' => 'public-health-healthcare-management',
];

/** Categories whose courses are also relevant to NGOs/government/donor-funded teams. */
$alsoCapacityBuilding = ['meal', 'public-health-healthcare-management', 'governance-risk-compliance',
    'project-management', 'procurement-logistics-supply-chain', 'legal-public-policy'];

function esc(?string $v): string
{
    if ($v === null) {
        return 'NULL';
    }
    return "'" . str_replace("'", "''", $v) . "'";
}

$sql = "-- Auto-generated by database/tools/import_courses.php from client-supplied course lists.\n";
$sql .= "-- Source: docs/content/source/ (Short_Professional_Courses.xlsx, More__Professional_Training_Courses.xlsx)\n";
$sql .= "-- Import after database/seed.sql.\n\n";
$sql .= "SET NAMES utf8mb4;\n\n";

$sql .= "INSERT INTO course_categories (slug, name, sort_order) VALUES\n";
$rows = [];
$i = 1;
foreach ($categories as $slug => $name) {
    $rows[] = "  (" . esc($slug) . ", " . esc($name) . ", $i)";
    $i++;
}
$sql .= implode(",\n", $rows) . "\nON DUPLICATE KEY UPDATE name = VALUES(name);\n\n";

$usedSlugs = [];
$courseRows = [];
$pillarLinkRows = [];

foreach ($courses as $c) {
    $title = trim($c['title']);
    $slugBase = Str::slug($title);
    $slug = $slugBase;
    $n = 2;
    while (isset($usedSlugs[$slug])) {
        $slug = $slugBase . '-' . $n;
        $n++;
    }
    $usedSlugs[$slug] = true;

    $categorySlug = $categoryMap[$c['category_raw'] ?? ''] ?? 'specialized-programmes';
    $programmeType = $c['programme_type'];
    $durationNote = $c['duration'] ?? null;
    $award = $c['award'] ?? 'Certificate of Completion';
    $priceAmount = $c['fee_ugx'] ?? null;
    $isPriced = $priceAmount !== null;

    $summary = $isPriced
        ? "A practical, {$award} programme" . ($durationNote ? " ({$durationNote})" : '') . '.'
        : "A customizable {$award} programme delivered on request for your organization.";

    $description = $isPriced
        ? "Practical, competency-based training in \"{$title}\", delivered by experienced CPI facilitators. "
            . "Leads to a {$award} from Crawford Professionals Institute (CPI)." . ($durationNote ? " Duration: {$durationNote}." : '')
        : "Available as part of CPI's corporate training catalogue — delivered in-house or customized for your "
            . "organization's needs. Request this topic via the corporate training request form and our team will "
            . "propose a schedule, venue and quotation.";

    $priceSql = $isPriced ? (string) (int) $priceAmount : '0';

    $courseRows[] = "INSERT INTO courses (category_id, title, slug, summary, description, programme_type, level, "
        . "duration_note, price_amount, price_currency, is_public, status) "
        . "SELECT c.id, " . esc($title) . ", " . esc($slug) . ", " . esc($summary) . ", " . esc($description) . ", "
        . esc($programmeType) . ", 'foundation', " . esc($durationNote) . ", $priceSql, 'UGX', 1, 'published' "
        . "FROM course_categories c WHERE c.slug = " . esc($categorySlug) . " "
        . "ON DUPLICATE KEY UPDATE title = VALUES(title);";

    $pillar = $programmeType === 'corporate' ? 'corporate-training' : 'professional-training';
    $pillarLinkRows[] = "INSERT INTO course_pillars (course_id, pillar_id) SELECT c.id, p.id FROM courses c, pillars p "
        . "WHERE c.slug = " . esc($slug) . " AND p.slug = " . esc($pillar) . " "
        . "ON DUPLICATE KEY UPDATE course_id = course_id;";

    if (in_array($categorySlug, $alsoCapacityBuilding, true)) {
        $pillarLinkRows[] = "INSERT INTO course_pillars (course_id, pillar_id) SELECT c.id, p.id FROM courses c, pillars p "
            . "WHERE c.slug = " . esc($slug) . " AND p.slug = 'capacity-building' "
            . "ON DUPLICATE KEY UPDATE course_id = course_id;";
    }
}

$sql .= "-- " . count($courseRows) . " courses\n";
$sql .= implode("\n", $courseRows) . "\n\n";
$sql .= "-- pillar links\n";
$sql .= implode("\n", $pillarLinkRows) . "\n\n";

// A handful of flagship courses get a demo/first intake so the catalogue and
// self-enrolment flow aren't empty on first deploy. Admin can add real dates
// for the rest (or edit these) from Admin > Courses.
$flagshipIntakes = [
    ['slug' => 'artificial-intelligence-for-professionals', 'code' => 'OCT-2026-EVENING', 'mode' => 'online', 'venue' => null, 'start' => '2026-10-13', 'end' => '2026-11-01', 'capacity' => 40],
    ['slug' => 'monitoring-and-evaluation-m-e', 'code' => 'NOV-2026-WEEKEND', 'mode' => 'hybrid', 'venue' => 'CPI Training Centre, Kampala', 'start' => '2026-11-07', 'end' => '2026-12-05', 'capacity' => 30],
    ['slug' => 'project-planning-and-management', 'code' => 'NOV-2026-WEEKEND', 'mode' => 'in_person', 'venue' => 'CPI Training Centre, Kampala', 'start' => '2026-11-14', 'end' => '2026-12-12', 'capacity' => 25],
];
$sql .= "-- flagship demo intakes (edit/replace via Admin > Courses)\n";
foreach ($flagshipIntakes as $fi) {
    $sql .= "INSERT INTO intakes (course_id, code, mode, venue, start_date, end_date, capacity, status) "
        . "SELECT id, " . esc($fi['code']) . ", " . esc($fi['mode']) . ", " . esc($fi['venue']) . ", "
        . esc($fi['start']) . ", " . esc($fi['end']) . ", " . (int) $fi['capacity'] . ", 'open' "
        . "FROM courses WHERE slug = " . esc($fi['slug']) . " "
        . "ON DUPLICATE KEY UPDATE status = VALUES(status);\n";
}

file_put_contents($output, $sql);
fwrite(STDOUT, "Wrote " . count($courseRows) . " courses to $output\n");
